version: "3.8"

services:
    app:
        build: .
        image: app:django4
        container_name: django4
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"